# docker-based Database Server.
# Start using: docker-compose up -d
# Stop using: docker-compose down

version: '3'
services:
  db:
    image: mysql/mysql-server:8.0.29-aarch64
    container_name: local-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    volumes:
      - /Users/zzyy/mysql:/var/lib/mysql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci



# docker pull --platform linux/amd64 mysql